-- HoodFlyLog moderated community fly-pattern library
-- REVIEW ONLY: this migration has not been executed.
--
-- Assumptions verified from the repository:
--   * public.profiles.id matches auth.users.id.
--   * public.is_moderator(uuid) already exists and recognizes moderators plus the
--     protected owner account. This migration deliberately creates no role-writing API.
--   * public.is_banned(uuid) already exists.
--   * The current private "My Flies" inventory lives in localStorage. Nothing in
--     this migration reads, changes, or replaces that data.
--   * Community images are uploaded only after a draft row exists, under:
--       <owner uuid>/<pattern uuid>/cover.<ext>
--       <owner uuid>/<pattern uuid>/steps/<step uuid>.<ext>

create extension if not exists pgcrypto;

-- Parent record and moderation lifecycle.
create table if not exists public.community_fly_patterns (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (length(btrim(name)) between 1 and 160),
  category text not null default 'Other' check (length(btrim(category)) between 1 and 80),
  summary text,
  best_for text,
  fishing_notes text,
  video_url text,
  cover_image_path text,
  status text not null default 'draft'
    check (status in ('draft', 'pending', 'published', 'rejected')),
  rejection_reason text,
  submitted_at timestamptz,
  published_at timestamptz,
  moderated_at timestamptz,
  moderated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint community_fly_patterns_video_provider check (
    video_url is null or video_url ~* '^https://(((www|m)\.)?youtube\.com/|youtu\.be/|(www\.)?vimeo\.com/|player\.vimeo\.com/)'
  ),
  constraint community_fly_patterns_cover_path check (
    cover_image_path is null
    or cover_image_path like owner_id::text || '/' || id::text || '/%'
  )
);

-- Materials and steps are normalized so ordering can be changed without storing
-- an opaque JSON recipe. A step may reference one private-bucket image.
create table if not exists public.community_fly_pattern_materials (
  id bigint generated by default as identity primary key,
  pattern_id uuid not null references public.community_fly_patterns(id) on delete cascade,
  position integer not null check (position > 0),
  name text not null check (length(btrim(name)) between 1 and 160),
  quantity text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (pattern_id, position)
);

create table if not exists public.community_fly_pattern_steps (
  id uuid primary key default gen_random_uuid(),
  pattern_id uuid not null references public.community_fly_patterns(id) on delete cascade,
  position integer not null check (position > 0),
  instruction text not null check (length(btrim(instruction)) > 0),
  image_path text,
  image_alt_text text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (pattern_id, position)
);

-- Audit rows survive pattern deletion. pattern_id becomes null, while
-- pattern_id_snapshot and pattern_snapshot retain what was acted upon.
create table if not exists public.community_fly_pattern_moderation_log (
  id bigint generated by default as identity primary key,
  pattern_id uuid references public.community_fly_patterns(id) on delete set null,
  pattern_id_snapshot uuid not null,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null check (
    action in ('submitted', 'published', 'rejected', 'moderator_edited', 'deleted')
  ),
  from_status text,
  to_status text,
  reason text,
  details jsonb not null default '{}'::jsonb,
  pattern_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists community_fly_patterns_public_idx
  on public.community_fly_patterns (published_at desc, created_at desc)
  where status = 'published';
create index if not exists community_fly_patterns_owner_idx
  on public.community_fly_patterns (owner_id, updated_at desc);
create index if not exists community_fly_patterns_queue_idx
  on public.community_fly_patterns (status, submitted_at asc);
create index if not exists community_fly_materials_pattern_idx
  on public.community_fly_pattern_materials (pattern_id, position);
create index if not exists community_fly_steps_pattern_idx
  on public.community_fly_pattern_steps (pattern_id, position);
create index if not exists community_fly_audit_pattern_idx
  on public.community_fly_pattern_moderation_log (pattern_id_snapshot, created_at desc);

-- Fixed-search-path SECURITY DEFINER helpers prevent callers from substituting
-- objects through search_path. They expose authorization decisions, not roles.
create or replace function public.can_read_community_fly_pattern(
  check_pattern_id uuid,
  check_user_id uuid default auth.uid()
) returns boolean
language sql stable security definer set search_path = ''
as $$
  select exists (
    select 1 from public.community_fly_patterns p
    where p.id = check_pattern_id
      and (
        p.status = 'published'
        or (check_user_id is not null and p.owner_id = check_user_id)
        or (check_user_id is not null and public.is_moderator(check_user_id))
      )
  );
$$;

create or replace function public.can_edit_community_fly_pattern(
  check_pattern_id uuid,
  check_user_id uuid default auth.uid()
) returns boolean
language sql stable security definer set search_path = ''
as $$
  select check_user_id is not null and exists (
    select 1 from public.community_fly_patterns p
    where p.id = check_pattern_id
      and (
        (p.owner_id = check_user_id and p.status in ('draft', 'rejected'))
        or public.is_moderator(check_user_id)
      )
  );
$$;

revoke all on function public.can_read_community_fly_pattern(uuid, uuid) from public;
grant execute on function public.can_read_community_fly_pattern(uuid, uuid) to anon, authenticated;
revoke all on function public.can_edit_community_fly_pattern(uuid, uuid) from public;
grant execute on function public.can_edit_community_fly_pattern(uuid, uuid) to authenticated;

-- updated_at maintenance. Child edits also touch the parent so list views and
-- caches see recipe changes.
create or replace function public.touch_community_fly_updated_at()
returns trigger language plpgsql set search_path = '' as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create or replace function public.touch_community_fly_parent()
returns trigger language plpgsql security definer set search_path = '' as $$
declare target_id uuid;
begin
  target_id := case when tg_op = 'DELETE' then old.pattern_id else new.pattern_id end;
  update public.community_fly_patterns set updated_at = now() where id = target_id;
  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

-- Non-moderators cannot forge ownership, moderation fields, or status changes.
-- Submission is performed by the audited RPC below.
create or replace function public.protect_community_fly_pattern_write()
returns trigger language plpgsql security definer set search_path = '' as $$
declare caller uuid := auth.uid();
declare moderator boolean := caller is not null and public.is_moderator(caller);
begin
  if caller is null then raise exception 'Authentication required'; end if;

  if tg_op = 'INSERT' then
    if not moderator then
      new.owner_id := caller;
      new.status := 'draft';
      new.rejection_reason := null;
      new.submitted_at := null;
      new.published_at := null;
      new.moderated_at := null;
      new.moderated_by := null;
      if public.is_banned(caller) then raise exception 'Banned users cannot create patterns'; end if;
    elsif new.owner_id is null then
      new.owner_id := caller;
    end if;
  else
    new.owner_id := old.owner_id;
    new.created_at := old.created_at;
    if not moderator then
      if old.owner_id <> caller or old.status not in ('draft', 'rejected') then
        raise exception 'Only editable drafts owned by the caller may be changed';
      end if;
      if coalesce(current_setting('hoodflylog.fly_workflow', true), '') <> 'submit'
         and new.status is distinct from old.status then
        raise exception 'Use submit_community_fly_pattern() to change status';
      end if;
      if coalesce(current_setting('hoodflylog.fly_workflow', true), '') <> 'submit' then
        new.rejection_reason := old.rejection_reason;
        new.submitted_at := old.submitted_at;
        new.published_at := old.published_at;
        new.moderated_at := old.moderated_at;
        new.moderated_by := old.moderated_by;
      end if;
    end if;
  end if;
  return new;
end;
$$;

-- Step paths must belong to the same owner/pattern directory as their parent.
create or replace function public.validate_community_fly_step_image_path()
returns trigger language plpgsql security definer set search_path = '' as $$
declare expected_prefix text;
begin
  if new.image_path is null then return new; end if;
  select p.owner_id::text || '/' || p.id::text || '/steps/' into expected_prefix
  from public.community_fly_patterns p where p.id = new.pattern_id;
  if expected_prefix is null or new.image_path not like expected_prefix || '%' then
    raise exception 'Step image path must be inside the pattern steps directory';
  end if;
  return new;
end;
$$;

-- Deletions are always logged, including an owner's draft deletion.
create or replace function public.audit_community_fly_pattern_delete()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if coalesce(current_setting('hoodflylog.skip_fly_delete_audit', true), '') <> 'on' then
    insert into public.community_fly_pattern_moderation_log
      (pattern_id, pattern_id_snapshot, actor_id, action, from_status, pattern_snapshot)
    values (old.id, old.id, auth.uid(), 'deleted', old.status, to_jsonb(old));
  end if;
  return old;
end;
$$;

drop trigger if exists community_fly_patterns_protect_write on public.community_fly_patterns;
create trigger community_fly_patterns_protect_write
  before insert or update on public.community_fly_patterns
  for each row execute function public.protect_community_fly_pattern_write();
drop trigger if exists community_fly_patterns_touch_updated_at on public.community_fly_patterns;
create trigger community_fly_patterns_touch_updated_at
  before update on public.community_fly_patterns
  for each row execute function public.touch_community_fly_updated_at();
drop trigger if exists community_fly_patterns_audit_delete on public.community_fly_patterns;
create trigger community_fly_patterns_audit_delete
  before delete on public.community_fly_patterns
  for each row execute function public.audit_community_fly_pattern_delete();

drop trigger if exists community_fly_materials_touch_updated_at on public.community_fly_pattern_materials;
create trigger community_fly_materials_touch_updated_at
  before update on public.community_fly_pattern_materials
  for each row execute function public.touch_community_fly_updated_at();
drop trigger if exists community_fly_materials_touch_parent on public.community_fly_pattern_materials;
create trigger community_fly_materials_touch_parent
  after insert or update or delete on public.community_fly_pattern_materials
  for each row execute function public.touch_community_fly_parent();

drop trigger if exists community_fly_steps_validate_image on public.community_fly_pattern_steps;
create trigger community_fly_steps_validate_image
  before insert or update on public.community_fly_pattern_steps
  for each row execute function public.validate_community_fly_step_image_path();
drop trigger if exists community_fly_steps_touch_updated_at on public.community_fly_pattern_steps;
create trigger community_fly_steps_touch_updated_at
  before update on public.community_fly_pattern_steps
  for each row execute function public.touch_community_fly_updated_at();
drop trigger if exists community_fly_steps_touch_parent on public.community_fly_pattern_steps;
create trigger community_fly_steps_touch_parent
  after insert or update or delete on public.community_fly_pattern_steps
  for each row execute function public.touch_community_fly_parent();

-- Audited workflow RPC: owners submit complete draft/rejected recipes.
create or replace function public.submit_community_fly_pattern(target_pattern_id uuid)
returns public.community_fly_patterns
language plpgsql security definer set search_path = '' as $$
declare caller uuid := auth.uid();
declare previous public.community_fly_patterns;
declare result public.community_fly_patterns;
begin
  if caller is null then raise exception 'Authentication required'; end if;
  if public.is_banned(caller) then raise exception 'Banned users cannot submit patterns'; end if;
  select * into previous from public.community_fly_patterns
    where id = target_pattern_id for update;
  if previous.id is null or previous.owner_id <> caller then raise exception 'Pattern not found'; end if;
  if previous.status not in ('draft', 'rejected') then raise exception 'Pattern is not submit-ready'; end if;
  if not exists (select 1 from public.community_fly_pattern_materials where pattern_id = target_pattern_id)
     or not exists (select 1 from public.community_fly_pattern_steps where pattern_id = target_pattern_id) then
    raise exception 'At least one material and one tying step are required';
  end if;
  perform set_config('hoodflylog.fly_workflow', 'submit', true);
  update public.community_fly_patterns set
    status = 'pending', submitted_at = now(), published_at = null,
    rejection_reason = null, moderated_at = null, moderated_by = null
    where id = target_pattern_id returning * into result;
  insert into public.community_fly_pattern_moderation_log
    (pattern_id, pattern_id_snapshot, actor_id, action, from_status, to_status, pattern_snapshot)
  values (result.id, result.id, caller, 'submitted', previous.status, result.status, to_jsonb(result));
  return result;
end;
$$;

-- Moderation decisions are centralized so status and audit data cannot diverge.
create or replace function public.moderate_community_fly_pattern(
  target_pattern_id uuid, decision text, moderation_reason text default null
) returns public.community_fly_patterns
language plpgsql security definer set search_path = '' as $$
declare caller uuid := auth.uid();
declare previous public.community_fly_patterns;
declare result public.community_fly_patterns;
begin
  if caller is null or not public.is_moderator(caller) then raise exception 'Moderator access required'; end if;
  if decision not in ('published', 'rejected') then raise exception 'Decision must be published or rejected'; end if;
  if decision = 'rejected' and nullif(btrim(moderation_reason), '') is null then
    raise exception 'A rejection reason is required';
  end if;
  select * into previous from public.community_fly_patterns where id = target_pattern_id for update;
  if previous.id is null then raise exception 'Pattern not found'; end if;
  if previous.status = 'draft' then raise exception 'The owner must submit this draft first'; end if;
  update public.community_fly_patterns set
    status = decision,
    rejection_reason = case when decision = 'rejected' then moderation_reason else null end,
    published_at = case when decision = 'published' then coalesce(published_at, now()) else null end,
    moderated_at = now(), moderated_by = caller
    where id = target_pattern_id returning * into result;
  insert into public.community_fly_pattern_moderation_log
    (pattern_id, pattern_id_snapshot, actor_id, action, from_status, to_status, reason, pattern_snapshot)
  values (result.id, result.id, caller, decision, previous.status, result.status,
          moderation_reason, to_jsonb(result));
  return result;
end;
$$;

-- Moderators edit parent metadata through a whitelist rather than receiving a
-- blanket UPDATE policy that could silently bypass moderation auditing.
create or replace function public.moderator_update_community_fly_pattern(
  target_pattern_id uuid, changes jsonb
) returns public.community_fly_patterns
language plpgsql security definer set search_path = '' as $$
declare caller uuid := auth.uid();
declare result public.community_fly_patterns;
begin
  if caller is null or not public.is_moderator(caller) then raise exception 'Moderator access required'; end if;
  update public.community_fly_patterns set
    name = case when changes ? 'name' then btrim(changes->>'name') else name end,
    category = case when changes ? 'category' then btrim(changes->>'category') else category end,
    summary = case when changes ? 'summary' then nullif(changes->>'summary', '') else summary end,
    best_for = case when changes ? 'best_for' then nullif(changes->>'best_for', '') else best_for end,
    fishing_notes = case when changes ? 'fishing_notes' then nullif(changes->>'fishing_notes', '') else fishing_notes end,
    video_url = case when changes ? 'video_url' then nullif(changes->>'video_url', '') else video_url end,
    cover_image_path = case when changes ? 'cover_image_path' then nullif(changes->>'cover_image_path', '') else cover_image_path end
    where id = target_pattern_id returning * into result;
  if result.id is null then raise exception 'Pattern not found'; end if;
  insert into public.community_fly_pattern_moderation_log
    (pattern_id, pattern_id_snapshot, actor_id, action, from_status, to_status, details, pattern_snapshot)
  values (result.id, result.id, caller, 'moderator_edited', result.status, result.status,
          jsonb_build_object('changed_keys', (select jsonb_agg(key) from jsonb_object_keys(changes) key)),
          to_jsonb(result));
  return result;
end;
$$;

create or replace function public.moderator_delete_community_fly_pattern(
  target_pattern_id uuid, deletion_reason text default null
) returns void
language plpgsql security definer set search_path = '' as $$
declare caller uuid := auth.uid();
declare target public.community_fly_patterns;
begin
  if caller is null or not public.is_moderator(caller) then raise exception 'Moderator access required'; end if;
  select * into target from public.community_fly_patterns where id = target_pattern_id for update;
  if target.id is null then raise exception 'Pattern not found'; end if;
  insert into public.community_fly_pattern_moderation_log
    (pattern_id, pattern_id_snapshot, actor_id, action, from_status, reason, pattern_snapshot)
  values (target.id, target.id, caller, 'deleted', target.status, deletion_reason, to_jsonb(target));
  perform set_config('hoodflylog.skip_fly_delete_audit', 'on', true);
  delete from public.community_fly_patterns where id = target_pattern_id;
end;
$$;

revoke all on function public.submit_community_fly_pattern(uuid) from public;
grant execute on function public.submit_community_fly_pattern(uuid) to authenticated;
revoke all on function public.moderate_community_fly_pattern(uuid, text, text) from public;
grant execute on function public.moderate_community_fly_pattern(uuid, text, text) to authenticated;
revoke all on function public.moderator_update_community_fly_pattern(uuid, jsonb) from public;
grant execute on function public.moderator_update_community_fly_pattern(uuid, jsonb) to authenticated;
revoke all on function public.moderator_delete_community_fly_pattern(uuid, text) from public;
grant execute on function public.moderator_delete_community_fly_pattern(uuid, text) to authenticated;

-- RLS: public sees published; owners see their own; moderators see the queue.
alter table public.community_fly_patterns enable row level security;
alter table public.community_fly_pattern_materials enable row level security;
alter table public.community_fly_pattern_steps enable row level security;
alter table public.community_fly_pattern_moderation_log enable row level security;

grant select on public.community_fly_patterns, public.community_fly_pattern_materials,
  public.community_fly_pattern_steps to anon, authenticated;
grant insert, update, delete on public.community_fly_patterns,
  public.community_fly_pattern_materials, public.community_fly_pattern_steps to authenticated;
grant select on public.community_fly_pattern_moderation_log to authenticated;
grant usage, select on sequence public.community_fly_pattern_materials_id_seq to authenticated;
grant usage, select on sequence public.community_fly_pattern_moderation_log_id_seq to authenticated;

drop policy if exists "community patterns readable by visibility" on public.community_fly_patterns;
drop policy if exists "published community patterns are public" on public.community_fly_patterns;
create policy "published community patterns are public" on public.community_fly_patterns
  for select to anon, authenticated using (status = 'published');
drop policy if exists "owners read their community patterns" on public.community_fly_patterns;
create policy "owners read their community patterns" on public.community_fly_patterns
  for select to authenticated using (owner_id = auth.uid());
drop policy if exists "moderators read all community patterns" on public.community_fly_patterns;
create policy "moderators read all community patterns" on public.community_fly_patterns
  for select to authenticated using (public.is_moderator(auth.uid()));
drop policy if exists "users create their own community drafts" on public.community_fly_patterns;
create policy "users create their own community drafts" on public.community_fly_patterns
  for insert to authenticated
  with check (owner_id = auth.uid() and status = 'draft' and not public.is_banned(auth.uid()));
drop policy if exists "owners update editable community drafts" on public.community_fly_patterns;
create policy "owners update editable community drafts" on public.community_fly_patterns
  for update to authenticated
  using (owner_id = auth.uid() and status in ('draft', 'rejected'))
  with check (owner_id = auth.uid() and status in ('draft', 'rejected'));
drop policy if exists "owners delete editable community drafts" on public.community_fly_patterns;
create policy "owners delete editable community drafts" on public.community_fly_patterns
  for delete to authenticated
  using (owner_id = auth.uid() and status in ('draft', 'rejected'));

drop policy if exists "community materials readable with pattern" on public.community_fly_pattern_materials;
create policy "community materials readable with pattern" on public.community_fly_pattern_materials
  for select to anon, authenticated using (public.can_read_community_fly_pattern(pattern_id));
drop policy if exists "community materials editable with pattern" on public.community_fly_pattern_materials;
create policy "community materials editable with pattern" on public.community_fly_pattern_materials
  for all to authenticated using (public.can_edit_community_fly_pattern(pattern_id))
  with check (public.can_edit_community_fly_pattern(pattern_id));

drop policy if exists "community steps readable with pattern" on public.community_fly_pattern_steps;
create policy "community steps readable with pattern" on public.community_fly_pattern_steps
  for select to anon, authenticated using (public.can_read_community_fly_pattern(pattern_id));
drop policy if exists "community steps editable with pattern" on public.community_fly_pattern_steps;
create policy "community steps editable with pattern" on public.community_fly_pattern_steps
  for all to authenticated using (public.can_edit_community_fly_pattern(pattern_id))
  with check (public.can_edit_community_fly_pattern(pattern_id));

drop policy if exists "owners and moderators read community audit" on public.community_fly_pattern_moderation_log;
create policy "owners and moderators read community audit" on public.community_fly_pattern_moderation_log
  for select to authenticated using (
    public.is_moderator(auth.uid())
    or pattern_snapshot->>'owner_id' = auth.uid()::text
  );
-- No client INSERT/UPDATE/DELETE audit policy exists; only trusted functions/triggers write it.

-- Private Storage bucket. Files are readable through storage.objects RLS only;
-- this prevents draft images from becoming public through guessable URLs.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'community-fly-pattern-images', 'community-fly-pattern-images', false, 5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do nothing;

create or replace function public.community_fly_pattern_id_from_storage_name(object_name text)
returns uuid language plpgsql immutable security definer set search_path = '' as $$
declare value text;
begin
  value := (storage.foldername(object_name))[2];
  if value is null or value !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' then
    return null;
  end if;
  return value::uuid;
end;
$$;
revoke all on function public.community_fly_pattern_id_from_storage_name(text) from public;
grant execute on function public.community_fly_pattern_id_from_storage_name(text) to anon, authenticated;

drop policy if exists "community fly images readable with pattern" on storage.objects;
create policy "community fly images readable with pattern" on storage.objects
  for select to anon, authenticated using (
    bucket_id = 'community-fly-pattern-images'
    and public.can_read_community_fly_pattern(public.community_fly_pattern_id_from_storage_name(name))
  );
drop policy if exists "community fly images insertable by editors" on storage.objects;
create policy "community fly images insertable by editors" on storage.objects
  for insert to authenticated with check (
    bucket_id = 'community-fly-pattern-images'
    and public.can_edit_community_fly_pattern(public.community_fly_pattern_id_from_storage_name(name))
    and (public.is_moderator(auth.uid()) or (storage.foldername(name))[1] = auth.uid()::text)
  );
drop policy if exists "community fly images updateable by editors" on storage.objects;
create policy "community fly images updateable by editors" on storage.objects
  for update to authenticated using (
    bucket_id = 'community-fly-pattern-images'
    and public.can_edit_community_fly_pattern(public.community_fly_pattern_id_from_storage_name(name))
  ) with check (
    bucket_id = 'community-fly-pattern-images'
    and public.can_edit_community_fly_pattern(public.community_fly_pattern_id_from_storage_name(name))
    and (public.is_moderator(auth.uid()) or (storage.foldername(name))[1] = auth.uid()::text)
  );
drop policy if exists "community fly images deletable by editors" on storage.objects;
create policy "community fly images deletable by editors" on storage.objects
  for delete to authenticated using (
    bucket_id = 'community-fly-pattern-images'
    and public.can_edit_community_fly_pattern(public.community_fly_pattern_id_from_storage_name(name))
  );

-- Storage objects are intentionally not deleted by SQL cascade. The application
-- should call the Storage API to remove a pattern directory before deleting its
-- database row; deleting storage.objects directly can leave underlying objects orphaned.
